import React, { useState } from "react";
import { useApp } from "../../context/AppContext";
import { Company } from "../../types";
import { Plus, Edit, Trash2, Shield, MapPin, Building } from "lucide-react";

export const CompanyList: React.FC = () => {
  const { companies, addCompany, updateCompany, deleteCompany } = useApp();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingCompany, setEditingCompany] = useState<Company | null>(null);

  // Form State
  const [formData, setFormData] = useState<Partial<Company>>({});

  const handleOpenModal = (company?: Company) => {
    if (company) {
      setEditingCompany(company);
      setFormData(company);
    } else {
      setEditingCompany(null);
      setFormData({
        country: "India",
        status: "Active",
        currency: "INR",
        timezone: "Asia/Kolkata",
        primaryColor: "#3A5BA0",
      });
    }
    setIsModalOpen(true);
  };

  const [loading, setLoading] = useState(false);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true); // 1. Start loading

    const now = new Date().toISOString();

    try {
      if (editingCompany) {
        // UPDATE
        await updateCompany({
          ...editingCompany,
          ...(formData as Company),
          updatedAt: now,
          updatedBy: "Super Admin",
        });
        alert("Company Updated Successfully!"); // Success Feedback
      } else {
        // CREATE
        await addCompany({
          ...(formData as Company),
          // tenantId will be generated by backend
        } as Company);
        alert("Company Created & Admin Invited!"); // Success Feedback
      }

      // 2. Close Modal ONLY if successful
      setIsModalOpen(false);
    } catch (error: any) {
      // 3. Catch Backend Error
      console.error("Save Failed:", error);

      // Extract the specific message from backend (e.g., "Email already exists")
      const errorMessage =
        error.response?.data?.message || "An error occurred while saving.";

      alert(`❌ Error: ${errorMessage}`);
    } finally {
      setLoading(false); // 4. Stop loading
    }
  };

  const handleDelete = (id: string, tenantId: string) => {
    if (!tenantId) {
      alert("Error: Cannot delete company without a Tenant ID.");
      return;
    }
    if (
      window.confirm(
        `Are you sure you want to delete tenant: ${tenantId}? \n\n⚠️ CRITICAL WARNING: This will delete ALL employees, branches, and data associated with this company.`
      )
    ) {
      // ✅ Call delete with the correct Tenant ID
      deleteCompany(id, tenantId);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">
            Client Companies
          </h1>
          <p className="text-slate-500 mt-1">
            Manage tenants and their access status.
          </p>
        </div>
        <button
          onClick={() => handleOpenModal()}
          className="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700"
        >
          <Plus className="h-4 w-4 mr-2" />
          Add Company
        </button>
      </div>

      {/* List */}
      <div className="bg-white shadow rounded-lg overflow-hidden border border-slate-200">
        <table className="min-w-full divide-y divide-slate-200">
          <thead className="bg-slate-50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                Company
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                Industry/Tax
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                Contact
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                Location
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                Status
              </th>
              <th className="px-6 py-3 text-right text-xs font-medium text-slate-500 uppercase tracking-wider">
                Actions
              </th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-slate-200">
            {(companies || []).map((company, index) => (
              <tr key={company.id || index} className="hover:bg-slate-50">
                <td className="px-6 py-4 whitespace-nowrap">
                  <div className="flex items-center">
                    <div
                      className="flex-shrink-0 h-10 w-10 rounded-md flex items-center justify-center text-white font-bold text-sm"
                      style={{
                        backgroundColor: company.primaryColor || "#999",
                      }}
                    >
                      {company.name
                        ? company.name.substring(0, 2).toUpperCase()
                        : "CO"}
                    </div>
                    <div className="ml-4">
                      <div className="text-sm font-medium text-slate-900">
                        {company.name}
                      </div>
                      <div className="text-xs text-slate-500">
                        ID: {company.tenantId}
                      </div>
                    </div>
                  </div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500">
                  <div className="font-medium text-slate-700">
                    {company.industry || "-"}
                  </div>
                  <div className="text-xs">PAN: {company.pan || "-"}</div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <div className="text-sm text-slate-900">
                    {company.contactPerson}
                  </div>
                  <div className="text-xs text-slate-500">{company.email}</div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500">
                  {company.city}, {company.state}
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <span
                    className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${
                      company.status === "Active"
                        ? "bg-green-100 text-green-800"
                        : "bg-slate-100 text-slate-800"
                    }`}
                  >
                    {company.status || "Active"}
                  </span>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium space-x-3">
                  <button
                    onClick={() => handleOpenModal(company)}
                    className="text-indigo-600 hover:text-indigo-900"
                    title="Edit"
                  >
                    <Edit className="h-4 w-4" />
                  </button>
                  <button
                    // Pass tenantId explicitly
                    onClick={() => handleDelete(company.id, company.tenantId)}
                    className="text-red-600 hover:text-red-900"
                    title="Delete"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Add/Edit Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 overflow-y-auto">
          <div className="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
            <div
              className="fixed inset-0 transition-opacity"
              aria-hidden="true"
            >
              <div
                className="absolute inset-0 bg-slate-900 opacity-75"
                onClick={() => setIsModalOpen(false)}
              ></div>
            </div>
            <span
              className="hidden sm:inline-block sm:align-middle sm:h-screen"
              aria-hidden="true"
            >
              &#8203;
            </span>
            <div className="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-4xl sm:w-full">
              <form onSubmit={handleSave}>
                <div className="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                  <h3 className="text-lg leading-6 font-bold text-slate-900 mb-6 border-b pb-2">
                    {editingCompany ? "Edit Company" : "Add New Company"}
                  </h3>

                  {/* Section: Basic Info */}
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
                    <div className="col-span-1 md:col-span-1">
                      <label className="block text-sm font-medium text-slate-700">
                        Identity
                      </label>
                      <p className="text-xs text-slate-500">
                        Core company details.
                      </p>
                    </div>
                    <div className="col-span-2 md:col-span-2 grid grid-cols-2 gap-4">
                      <div className="col-span-2 sm:col-span-1">
                        <label className="block text-sm font-medium text-slate-700">
                          Company Name *
                        </label>
                        <input
                          required
                          type="text"
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 focus:ring-indigo-500 sm:text-sm"
                          value={formData.name || ""}
                          onChange={(e) =>
                            setFormData({ ...formData, name: e.target.value })
                          }
                        />
                      </div>
                      <div className="col-span-2 sm:col-span-1">
                        <label className="block text-sm font-medium text-slate-700">
                          Industry
                        </label>
                        <input
                          type="text"
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 sm:text-sm"
                          value={formData.industry || ""}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              industry: e.target.value,
                            })
                          }
                        />
                      </div>
                      <div className="col-span-2">
                        <label className="block text-sm font-medium text-slate-700">
                          Legal Name
                        </label>
                        <input
                          type="text"
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 sm:text-sm"
                          value={formData.legalName || ""}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              legalName: e.target.value,
                            })
                          }
                        />
                      </div>
                      <div className="col-span-2 sm:col-span-1">
                        <label className="block text-sm font-medium text-slate-700">
                          Status
                        </label>
                        <select
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 sm:text-sm"
                          value={formData.status || "Active"}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              status: e.target.value as any,
                            })
                          }
                        >
                          <option value="Active">Active</option>
                          <option value="Inactive">Inactive</option>
                        </select>
                      </div>
                      <div className="col-span-2 sm:col-span-1">
                        <label className="block text-sm font-medium text-slate-700">
                          Brand Color
                        </label>
                        <div className="flex items-center mt-1">
                          <input
                            type="color"
                            className="h-9 w-16 p-0 border border-slate-300 rounded"
                            value={formData.primaryColor || "#3A5BA0"}
                            onChange={(e) =>
                              setFormData({
                                ...formData,
                                primaryColor: e.target.value,
                              })
                            }
                          />
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Section: Contact & Address */}
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6 border-t pt-6">
                    <div className="col-span-1 md:col-span-1">
                      <label className="block text-sm font-medium text-slate-700">
                        Contact & Location
                      </label>
                      <p className="text-xs text-slate-500">
                        Primary contact and HQ.
                      </p>
                    </div>
                    <div className="col-span-2 md:col-span-2 grid grid-cols-2 gap-4">
                      <div className="col-span-2 sm:col-span-1">
                        <label className="block text-sm font-medium text-slate-700">
                          Contact Person
                        </label>
                        <input
                          type="text"
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 sm:text-sm"
                          value={formData.contactPerson || ""}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              contactPerson: e.target.value,
                            })
                          }
                        />
                      </div>
                      <div className="col-span-2 sm:col-span-1">
                        <label className="block text-sm font-medium text-slate-700">
                          Email *
                        </label>
                        <input
                          required
                          type="email"
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 sm:text-sm"
                          value={formData.email || ""}
                          onChange={(e) =>
                            setFormData({ ...formData, email: e.target.value })
                          }
                        />
                      </div>
                      <div className="col-span-2">
                        <label className="block text-sm font-medium text-slate-700">
                          Address
                        </label>
                        <input
                          type="text"
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 sm:text-sm"
                          value={formData.addressLine1 || ""}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              addressLine1: e.target.value,
                            })
                          }
                        />
                      </div>
                      <div className="col-span-2 sm:col-span-1">
                        <label className="block text-sm font-medium text-slate-700">
                          City
                        </label>
                        <input
                          type="text"
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 sm:text-sm"
                          value={formData.city || ""}
                          onChange={(e) =>
                            setFormData({ ...formData, city: e.target.value })
                          }
                        />
                      </div>
                      <div className="col-span-2 sm:col-span-1">
                        <label className="block text-sm font-medium text-slate-700">
                          State
                        </label>
                        <input
                          type="text"
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 sm:text-sm"
                          value={formData.state || ""}
                          onChange={(e) =>
                            setFormData({ ...formData, state: e.target.value })
                          }
                        />
                      </div>
                      <div className="col-span-2 sm:col-span-1">
                        <label className="block text-sm font-medium text-slate-700">
                          Country
                        </label>
                        <input
                          type="text"
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 sm:text-sm"
                          value={formData.country || "India"}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              country: e.target.value,
                            })
                          }
                        />
                      </div>
                      <div className="col-span-2 sm:col-span-1">
                        <label className="block text-sm font-medium text-slate-700">
                          Pincode
                        </label>
                        <input
                          type="text"
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 sm:text-sm"
                          value={formData.pincode || ""}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              pincode: e.target.value,
                            })
                          }
                        />
                      </div>
                    </div>
                  </div>

                  {/* Section: Statutory */}
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6 border-t pt-6">
                    <div className="col-span-1 md:col-span-1">
                      <label className="block text-sm font-medium text-slate-700">
                        Statutory
                      </label>
                      <p className="text-xs text-slate-500">
                        Tax and legal IDs.
                      </p>
                    </div>
                    <div className="col-span-2 md:col-span-2 grid grid-cols-3 gap-4">
                      <div className="col-span-1">
                        <label className="block text-sm font-medium text-slate-700">
                          PAN
                        </label>
                        <input
                          type="text"
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 sm:text-sm"
                          value={formData.pan || ""}
                          onChange={(e) =>
                            setFormData({ ...formData, pan: e.target.value })
                          }
                        />
                      </div>
                      <div className="col-span-1">
                        <label className="block text-sm font-medium text-slate-700">
                          GSTIN
                        </label>
                        <input
                          type="text"
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 sm:text-sm"
                          value={formData.gstin || ""}
                          onChange={(e) =>
                            setFormData({ ...formData, gstin: e.target.value })
                          }
                        />
                      </div>
                      <div className="col-span-1">
                        <label className="block text-sm font-medium text-slate-700">
                          CIN
                        </label>
                        <input
                          type="text"
                          className="mt-1 block w-full border border-slate-300 rounded-md py-2 px-3 sm:text-sm"
                          value={formData.cin || ""}
                          onChange={(e) =>
                            setFormData({ ...formData, cin: e.target.value })
                          }
                        />
                      </div>
                    </div>
                  </div>
                </div>
                <div className="bg-slate-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                  <button
                    type="submit"
                    disabled={loading}
                    className={`w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-indigo-600 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none sm:ml-3 sm:w-auto sm:text-sm ${
                      loading ? "opacity-50 cursor-not-allowed" : ""
                    }`}
                  >
                    {loading ? "Processing..." : "Save Company"}
                  </button>
                  <button
                    type="button"
                    className="mt-3 w-full inline-flex justify-center rounded-md border border-slate-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-slate-700 hover:bg-slate-50 focus:outline-none sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
                    onClick={() => setIsModalOpen(false)}
                  >
                    Cancel
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
